version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: uddisharma/thribute:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend_network
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://127.0.0.1:27017/EcomDb_test
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mongo_data:
