export const commoncolors = [
  { name: 'Red', value: 'Red' },
  { name: 'Blue', value: 'Blue' },
  { name: 'Green', value: 'Green' },
  { name: 'Yellow', value: 'Yellow' },
  { name: 'Orange', value: 'Orange' },
  { name: 'Purple', value: 'Purple' },
  { name: 'Pink', value: 'Pink' },
  { name: 'Brown', value: 'Brown' },
  { name: 'White', value: 'White' },
  { name: 'Gray', value: 'Gray' },
  { name: 'Black', value: 'Black' },
  { name: 'Beige', value: 'Beige' },
  { name: 'Cyan', value: 'Cyan' },
  { name: 'Magenta', value: 'Magenta' },
  { name: 'Teal', value: 'Teal' },
  { name: 'Lime', value: 'Lime' },
  { name: 'Maroon', value: 'Maroon' },
  { name: 'Navy', value: 'Navy' },
  { name: 'Olive', value: 'Olive' },
  { name: 'Silver', value: 'Silver' },
  { name: 'Color Free', value: 'Color Free' },
];

export const commonSizes = [
  { name: 'XS', value: 'XS' },
  { name: 'SM', value: 'SM' },
  { name: 'MD', value: 'MD' },
  { name: 'LG', value: 'LG' },
  { name: 'XL', value: 'XL' },
  { name: 'XXL', value: 'XXL' },
  { name: 'XXXL', value: 'XXXL' },
  { name: '1', value: '1' },
  { name: '2', value: '2' },
  { name: '3', value: '3' },
  { name: '4', value: '4' },
  { name: '5', value: '5' },
  { name: '6', value: '6' },
  { name: '7', value: '7' },
  { name: '8', value: '8' },
  { name: '9', value: '9' },
  { name: '10', value: '10' },
  { name: '36', value: '36' },
  { name: '37', value: '37' },
  { name: '38', value: '38' },
  { name: '39', value: '39' },
  { name: '40', value: '40' },
  { name: '41', value: '41' },
  { name: '42', value: '42' },
  { name: '43', value: '43' },
  { name: '44', value: '44' },
  { name: '45', value: '45' },
  { name: '46', value: '46' },
  { name: '47', value: '47' },
  { name: '48', value: '48' },
  { name: 'Size Free', value: 'Size Free' },
];
